import type { OrganizationMember } from './organizations.types'

export const organizationMockMembers: OrganizationMember[] = [
  {
    id: 'u-001',
    userCode: 'A0001',
    userName: 'Nguyễn Văn Tổng',
    roleName: 'General Director',
    areaName: 'Head Office',
    parentId: null,
    email: 'tong.nguyen@jiahsin.com.vn',
    phone: '0901 000 001',
    active: true,
    order: 1,
  },
  {
    id: 'u-002',
    userCode: 'A0002',
    userName: 'Trần Thị An',
    roleName: 'Operations Manager',
    areaName: 'JHV',
    parentId: 'u-001',
    email: 'an.tran@jiahsin.com.vn',
    phone: '0901 000 002',
    active: true,
    order: 2,
  },
  {
    id: 'u-003',
    userCode: 'A0003',
    userName: 'Lê Minh Khang',
    roleName: 'IT Manager',
    areaName: 'SHM',
    parentId: 'u-001',
    email: 'khang.le@jiahsin.com.vn',
    phone: '0901 000 003',
    active: true,
    order: 3,
  },
  {
    id: 'u-004',
    userCode: 'A0004',
    userName: 'Phạm Quốc Dũng',
    roleName: 'Security Supervisor',
    areaName: 'JHV',
    parentId: 'u-002',
    email: 'dung.pham@jiahsin.com.vn',
    phone: '0901 000 004',
    active: true,
    order: 4,
  },
  {
    id: 'u-005',
    userCode: 'A0005',
    userName: 'Hoàng Gia Hân',
    roleName: 'Area Supervisor',
    areaName: 'SHM',
    parentId: 'u-002',
    email: 'han.hoang@jiahsin.com.vn',
    phone: '0901 000 005',
    active: true,
    order: 5,
  },
  {
    id: 'u-006',
    userCode: 'A0006',
    userName: 'Đặng Hải Long',
    roleName: 'System Analyst',
    areaName: 'SHM',
    parentId: 'u-003',
    email: 'long.dang@jiahsin.com.vn',
    phone: '0901 000 006',
    active: true,
    order: 6,
  },
  {
    id: 'u-007',
    userCode: 'A0007',
    userName: 'Bùi Khánh Vy',
    roleName: 'Frontend Developer',
    areaName: 'SHM',
    parentId: 'u-003',
    email: 'vy.bui@jiahsin.com.vn',
    phone: '0901 000 007',
    active: true,
    order: 7,
  },
  {
    id: 'u-008',
    userCode: 'A0008',
    userName: 'Trương Nhật Huy',
    roleName: 'Patrol Leader',
    areaName: 'JHV',
    parentId: 'u-004',
    email: 'huy.truong@jiahsin.com.vn',
    phone: '0901 000 008',
    active: true,
    order: 8,
  },
  {
    id: 'u-009',
    userCode: 'A0009',
    userName: 'Ngô Thanh Bình',
    roleName: 'Patrol Leader',
    areaName: 'JHV',
    parentId: 'u-004',
    email: 'binh.ngo@jiahsin.com.vn',
    phone: '0901 000 009',
    active: true,
    order: 9,
  },
  {
    id: 'u-010',
    userCode: 'A0010',
    userName: 'Phan Mỹ Linh',
    roleName: 'Route Coordinator',
    areaName: 'SHM',
    parentId: 'u-005',
    email: 'linh.phan@jiahsin.com.vn',
    phone: '0901 000 010',
    active: true,
    order: 10,
  },
  {
    id: 'u-011',
    userCode: 'A0011',
    userName: 'Võ Đức Nam',
    roleName: 'Backend Developer',
    areaName: 'SHM',
    parentId: 'u-006',
    email: 'nam.vo@jiahsin.com.vn',
    phone: '0901 000 011',
    active: true,
    order: 11,
  },
  {
    id: 'u-012',
    userCode: 'A0012',
    userName: 'Lý Thanh Tâm',
    roleName: 'QA Engineer',
    areaName: 'SHM',
    parentId: 'u-006',
    email: 'tam.ly@jiahsin.com.vn',
    phone: '0901 000 012',
    active: true,
    order: 12,
  },
]
